In [16]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
dataset = pd.read_csv('data1.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [18]:
print(X)

[['Yudi' 38.0 2000000.0]
 ['Slamet' nan 1800000.0]
 ['Herman' 34.0 2200000.0]
 ['Yudi' 34.0 2800000.0]
 ['Slamet' 37.0 3200000.0]
 ['Herman' 29.0 2900000.0]
 ['Yudi' 37.0 2700000.0]
 ['Slamet' 38.0 2000000.0]
 ['Herman' 28.0 1900000.0]
 ['Yudi' nan nan]]


In [19]:
print(Y)

['true;' 'false;' 'true;' 'false;' 'false;' 'true;' 'true;' 'false;'
 'false;' 'false;']


In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [21]:
print(X)

[['Yudi' 38.0 2000000.0]
 ['Slamet' 34.375 1800000.0]
 ['Herman' 34.0 2200000.0]
 ['Yudi' 34.0 2800000.0]
 ['Slamet' 37.0 3200000.0]
 ['Herman' 29.0 2900000.0]
 ['Yudi' 37.0 2700000.0]
 ['Slamet' 38.0 2000000.0]
 ['Herman' 28.0 1900000.0]
 ['Yudi' 34.375 2388888.888888889]]


In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
print(X)

[[1.0 0.0 0.0 1.0 38.0 2000000.0]
 [1.0 0.0 1.0 0.0 34.375 1800000.0]
 [0.0 1.0 0.0 0.0 34.0 2200000.0]
 [1.0 0.0 0.0 1.0 34.0 2800000.0]
 [1.0 0.0 1.0 0.0 37.0 3200000.0]
 [0.0 1.0 0.0 0.0 29.0 2900000.0]
 [1.0 0.0 0.0 1.0 37.0 2700000.0]
 [1.0 0.0 1.0 0.0 38.0 2000000.0]
 [0.0 1.0 0.0 0.0 28.0 1900000.0]
 [1.0 0.0 0.0 1.0 34.375 2388888.888888889]]


In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [26]:
print(Y)

[1 0 1 0 0 1 1 0 0 0]


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 1)

In [28]:
print(X_train)

[[1.0 0.0 0.0 1.0 37.0 2700000.0]
 [1.0 0.0 1.0 0.0 37.0 3200000.0]
 [1.0 0.0 0.0 1.0 38.0 2000000.0]
 [1.0 0.0 0.0 1.0 34.0 2800000.0]
 [1.0 0.0 1.0 0.0 34.375 1800000.0]
 [1.0 0.0 1.0 0.0 38.0 2000000.0]
 [0.0 1.0 0.0 0.0 28.0 1900000.0]
 [0.0 1.0 0.0 0.0 29.0 2900000.0]]


In [29]:
print(X_test)

[[0.0 1.0 0.0 0.0 34.0 2200000.0]
 [1.0 0.0 0.0 1.0 34.375 2388888.888888889]]


In [30]:
print(Y_train)

[1 0 1 0 0 0 0 1]


In [31]:
print(Y_test)

[1 0]


In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [33]:
print(X_train)

[[1.0 0.0 0.0 1.2909944487358056 0.6961653502771944 0.5653648929988928]
 [1.0 0.0 1.0 -0.7745966692414834 0.6961653502771944 1.5486081851708804]
 [1.0 0.0 0.0 1.2909944487358056 0.9661931225059243 -0.8111757160418898]
 [1.0 0.0 0.0 1.2909944487358056 -0.11391796640899544 0.7620135514332904]
 [1.0 0.0 1.0 -0.7745966692414834 -0.012657551823221716
  -1.2044730329106847]
 [1.0 0.0 1.0 -0.7745966692414834 0.9661931225059243 -0.8111757160418898]
 [0.0 1.0 0.0 -0.7745966692414834 -1.734084599781375 -1.0078243744762871]
 [0.0 1.0 0.0 -0.7745966692414834 -1.464056827552645 0.9586622098676879]]


In [34]:
print(X_test)

[[0.0 1.0 0.0 -0.7745966692414834 -0.11391796640899544
  -0.4178783991730947]
 [1.0 0.0 0.0 1.2909944487358056 -0.012657551823221716
  -0.046430933241454767]]
